name: 'Six&Seven'
favicon: null
layout_spectrum: 0.74397
typography_spectrum: 0.25371
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.6875
  lightness: 0.6848557277116925
  saturation: 0.2939636807423085
  rhythmicContrast: 0.7324826384428889
purpose: []
